<script lang="ts">
  import { onMount } from "svelte";
  import { FolderKanban, Plus, Save, Trash2 } from "@lucide/svelte";
  import * as Card from "$lib/components/ui/card/index.js";
  import { Button } from "$lib/components/ui/button/index.js";
  import { Input } from "$lib/components/ui/input/index.js";
  import * as Label from "$lib/components/ui/label/index.js";
  import { deleteStudioProject, listStudioProjects, listStudioResources, saveStudioProject, setStudioProjectResources } from "../lib/mantleApi";
  import type { StudioProject, StudioResource } from "../lib/types";
  import { activeStudioProject } from "../stores/studioProject";

  let projects=$state<StudioProject[]>([]),resources=$state<StudioResource[]>([]),selectedID=$state(""),name=$state(""),description=$state(""),selectedPaths=$state<string[]>([]),error=$state(""),busy=$state(false);
  let selected=$derived(projects.find((item)=>item.id===selectedID));
  let grouped=$derived(Object.entries(Object.groupBy(resources,(resource)=>resource.type)));
  async function refresh(){busy=true;try{[projects,resources]=await Promise.all([listStudioProjects(),listStudioResources()]);error=""}catch(cause){error=cause instanceof Error?cause.message:String(cause)}finally{busy=false}}
  function load(project:StudioProject){selectedID=project.id;name=project.name;description=project.description??"";selectedPaths=[...project.resources]}
  function create(){selectedID="";name="New project";description="";selectedPaths=[]}
  function toggle(path:string,checked:boolean){selectedPaths=checked?[...selectedPaths,path]:selectedPaths.filter((item)=>item!==path)}
  async function save(){busy=true;try{const project=await saveStudioProject({id:selectedID||undefined,name,description});await setStudioProjectResources(project.id,selectedPaths);await refresh();load((await listStudioProjects()).find((item)=>item.id===project.id)??project);error=""}catch(cause){error=cause instanceof Error?cause.message:String(cause)}finally{busy=false}}
  async function remove(){if(!selected||!confirm(`Delete project ${selected.name}? Resources are not deleted.`))return;busy=true;try{await deleteStudioProject(selected.id);if($activeStudioProject===selected.id)activeStudioProject.set("");selectedID="";name="";description="";selectedPaths=[];await refresh()}catch(cause){error=cause instanceof Error?cause.message:String(cause)}finally{busy=false}}
  onMount(refresh);
</script>
<div class="h-full overflow-auto p-4"><div class="mx-auto max-w-7xl space-y-4"><div class="flex items-center gap-2"><FolderKanban class="size-5"/><h2 class="text-lg font-semibold">Studio projects</h2><Button class="ml-auto" onclick={create}><Plus class="size-4"/>New project</Button></div><p class="text-muted-foreground text-sm">An active project groups new jobs, produced artifacts, and saved recipes. Resource references make its models and datasets easy to find without moving or deleting files.</p>{#if error}<p class="text-destructive text-sm">{error}</p>{/if}<div class="grid gap-4 lg:grid-cols-[18rem_1fr]"><Card.Root class="h-fit"><Card.Header><Card.Title>Projects</Card.Title></Card.Header><Card.Content class="space-y-2">{#if !projects.length}<p class="text-muted-foreground text-sm">No projects yet.</p>{/if}{#each projects as project(project.id)}<button type="button" class="hover:bg-muted w-full rounded-md border p-2 text-left" class:border-primary={project.id===selectedID} onclick={()=>load(project)}><span class="block text-sm font-medium">{project.name}{#if $activeStudioProject === project.id} · active{/if}</span><span class="text-muted-foreground text-xs">{project.resources.length} resources</span></button>{/each}</Card.Content></Card.Root><Card.Root><Card.Header><Card.Title>{selectedID?"Edit project":"Create project"}</Card.Title><Card.Description>Deleting a project never deletes its files or jobs.</Card.Description></Card.Header><Card.Content class="space-y-4"><div class="grid gap-3 sm:grid-cols-2"><div class="space-y-1"><Label.Root for="project-name">Name</Label.Root><Input id="project-name" bind:value={name}/></div><div class="space-y-1"><Label.Root for="project-description">Description</Label.Root><Input id="project-description" bind:value={description}/></div></div>{#each grouped as [type,items]}<div><h3 class="mb-2 text-sm font-medium capitalize">{type}s</h3><div class="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{#each items??[] as resource(resource.path)}<label class="flex min-w-0 items-center gap-2 rounded-md border p-2 text-sm"><input type="checkbox" checked={selectedPaths.includes(resource.path)} onchange={(event)=>toggle(resource.path,event.currentTarget.checked)}/><span class="min-w-0"><span class="block truncate">{resource.path}</span><span class="text-muted-foreground text-xs">{resource.kind}</span></span></label>{/each}</div></div>{/each}<div class="flex flex-wrap justify-end gap-2">{#if selectedID}<Button variant="outline" onclick={() => activeStudioProject.set(selectedID)} disabled={$activeStudioProject === selectedID}>Use as active project</Button><Button variant="destructive" onclick={remove} disabled={busy}><Trash2 class="size-4"/>Delete project</Button>{/if}<Button onclick={save} disabled={busy||!name.trim()}><Save class="size-4"/>Save project</Button></div></Card.Content></Card.Root></div></div></div>
